# 通用部分配置
spring:
  profiles:
    # 当前激活的配置文件
    #active: xiang
    active: han
    #active: wen

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    # 资源文件夹映射到url的
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    # 开启mybatis驼峰转换
    map-underscore-to-camel-case: true

#前端所使用的服务器地址 默认应http://localhost:8080/
domain: https://sodacooky.plus:8080/

---
spring:
  config:
    activate:
      on-profile: wen
  datasource:
    username: root
    password: 123456



---
spring:
  config:
    activate:
      on-profile: han
  datasource:
    url: jdbc:mysql://sodacooky.plus:3306/bgb
    username: bgb
    password: 114514
server:
  port: 8081



---
spring:
  config:
    activate:
      on-profile: xiang
  datasource:
    url: jdbc:mysql://sodacooky.plus:3306/bgb
    username: bgb
    password: 114514
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:D:\_Work\JavaRepository\BigGreenBook\data
#DEBUGING
logging:
  level:
    main.biggreenbook.entity.dao.*: debug


---
#部署环境，Linux Debian 11
spring:
  config:
    activate:
      on-profile: product
  datasource:
    url: jdbc:mysql://localhost:3306/bgb
    username: bgb
    password: 114514
    hikari:
      max-lifetime: 90000
  web:
    resources:
      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:/root/bgb_test/res
server:
  ssl:
    key-store: classpath:bgb.p12
    key-store-type: pkcs12
    key-store-password: 114514
logging:
  file:
    path: ./log
